// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/friends": {
    params: {};
  };
  "/shop": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/groups/:id": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/dashboard" | "/friends" | "/shop" | "/profile" | "/groups/:id" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/friends.tsx": {
    id: "routes/friends";
    page: "/friends";
  };
  "routes/shop.tsx": {
    id: "routes/shop";
    page: "/shop";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/groups.$id.tsx": {
    id: "routes/groups.$id";
    page: "/groups/:id";
  };
  "routes/[...404].tsx": {
    id: "routes/[...404]";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/friends": typeof import("./app/routes/friends.tsx");
  "routes/shop": typeof import("./app/routes/shop.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/groups.$id": typeof import("./app/routes/groups.$id.tsx");
  "routes/[...404]": typeof import("./app/routes/[...404].tsx");
};